#
POST http://localhost:3000/users/create
Content-Type: application/json

{
    "lastname" : "moussia",
    "firstname" : "hhjn",
    "email" : "cocohu@gmail.com",
    "password" : ""
}

### FAUX PASS
POST http://localhost:3000/session
Content-Type: application/json

{
    "email" : "moussiamottal@gmail.com",
    "password" : "coco"
}

### FAUX MAIL
POST http://localhost:3000/session
Content-Type: application/json

{
    "email" : "moussiamsottal@gmail.com",
    "password" : "coco"
}


### Faux Mail et Faux mot de passe
POST http://localhost:3000/session
Content-Type: application/json

{
    "email" : "moussiamodgbusjkgdbttal@gmail.com",
    "password" : "bla"
}

### Bonne connexion
POST http://localhost:3000/session
Content-Type: application/json

{
    "email" : "moussiamottal@gmail.com",
    "password" : "Azertyuio1/"
}

### 
GET http://localhost:3000/user/current


### 
DELETE http://localhost:3000/session